//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.Sap;
using CMS.CustomTables;

[assembly: RegisterCustomTable(Episodes_CustomTableItem.CLASS_NAME, typeof(Episodes_CustomTableItem))]

namespace CMS.CustomTables.Types.Sap
{
    /// <summary>
    /// Represents a content item of type Episodes_CustomTableItem.
    /// </summary>
    public partial class Episodes_CustomTableItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "Sap.Episodes_CustomTable";


        /// <summary>
        /// The instance of the class that provides extended API for working with Episodes_CustomTableItem fields.
        /// </summary>
        private readonly Episodes_CustomTableItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// What episode number is this.
        /// </summary>
        [DatabaseField]
        public int EpisodeNumber
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("EpisodeNumber"), 0);
            }
            set
            {
                SetValue("EpisodeNumber", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string ImageUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ImageUrl"), @"");
            }
            set
            {
                SetValue("ImageUrl", value);
            }
        }


        /// <summary>
        /// Chapter.
        /// </summary>
        [DatabaseField]
        public string Chapter
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Chapter"), @"");
            }
            set
            {
                SetValue("Chapter", value);
            }
        }


        /// <summary>
        /// Commentary.
        /// </summary>
        [DatabaseField]
        public string Commentary
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Commentary"), @"");
            }
            set
            {
                SetValue("Commentary", value);
            }
        }


        /// <summary>
        /// Date.
        /// </summary>
        [DatabaseField]
        public DateTime Date
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("Date"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("Date", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Episodes_CustomTableItem fields.
        /// </summary>
        [RegisterProperty]
        public Episodes_CustomTableItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Episodes_CustomTableItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class Episodes_CustomTableItemFields : AbstractHierarchicalObject<Episodes_CustomTableItemFields>
        {
            /// <summary>
            /// The content item of type Episodes_CustomTableItem that is a target of the extended API.
            /// </summary>
            private readonly Episodes_CustomTableItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="Episodes_CustomTableItemFields" /> class with the specified content item of type Episodes_CustomTableItem.
            /// </summary>
            /// <param name="instance">The content item of type Episodes_CustomTableItem that is a target of the extended API.</param>
            public Episodes_CustomTableItemFields(Episodes_CustomTableItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// What episode number is this.
            /// </summary>
            public int EpisodeNumber
            {
                get
                {
                    return mInstance.EpisodeNumber;
                }
                set
                {
                    mInstance.EpisodeNumber = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string ImageUrl
            {
                get
                {
                    return mInstance.ImageUrl;
                }
                set
                {
                    mInstance.ImageUrl = value;
                }
            }


            /// <summary>
            /// Chapter.
            /// </summary>
            public string Chapter
            {
                get
                {
                    return mInstance.Chapter;
                }
                set
                {
                    mInstance.Chapter = value;
                }
            }


            /// <summary>
            /// Commentary.
            /// </summary>
            public string Commentary
            {
                get
                {
                    return mInstance.Commentary;
                }
                set
                {
                    mInstance.Commentary = value;
                }
            }


            /// <summary>
            /// Date.
            /// </summary>
            public DateTime Date
            {
                get
                {
                    return mInstance.Date;
                }
                set
                {
                    mInstance.Date = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Episodes_CustomTableItem" /> class.
        /// </summary>
        public Episodes_CustomTableItem() : base(CLASS_NAME)
        {
            mFields = new Episodes_CustomTableItemFields(this);
        }

        #endregion
    }
}